<MainMenuScreen>:
	BoxLayout:
		orientation: "vertical"
		Button:
			text: "Play music"
			font_size: dp(50)
			on_release: root.manager.current = "music"
		Label:
			text: "Music"
			font_size: dp(50)
			
<MusicScreen>:
	BoxLayout:
		orientation: "horizontal"
		Button:
			text: "Play the file"
			font_size: dp(50)
			on_release: root.playMusic()
		Button:
			text: "Go back to main menu"
			font_size: dp(30)
			on_release: root.manager.current = "main_menu"
			